[package]
name = "egui-notify"
version = "0.5.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/ItsEthra/egui-notify"
description = "Simple notifications library for EGUI"
authors = ["ItsEthra"]
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
egui = "0.20"

[dev-dependencies]
eframe = "0.20"


[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", rev = "8ce0e1c5206780e76234842b94ceb0edf5bb8b75" } # egui master 2023-01-25 - DON'T MERGE THIS!
